name: Part C-1. linux.yml

on:
  push:
    paths:
      - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Get commit number
      id: vars
      run: |
        cd linux
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        cd ..

    - name: Download and unzip linux repository, and build the unzipped source code
        shell: bash
        run: |
          wget https://github.com/Choi/linux/archive/${{ steps.vars.outputs.sha_short }}.zip -O linux.zip
          unzip linux.zip
          ./build-linux.sh linux tinyconfig
