name: Part C-1. linux.yml

on:
  push:
    paths:
      - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Get commit number
      id: vars
      run: echo "::set-output name=sha_short::$(echo $(git submodule) | cut -d' ' -f1)" 
      working-directory: linux
      
    - name: Download and unzip linux repository, and build the unzipped source code
      shell: bash
      run: |
        wget https://github.com/ChoiDM/linux/archive/${{ steps.vars.outputs.sha_short }}.zip -O linux.zip
        unzip linux.zip
        ./build-linux.sh linux tinyconfig
