name: Part C-1. linux.yml

on:
  push:
    paths:
      - linux
      - linux/**
      - linux/*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Get commit number
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse HEAD:linux)" 
      working-directory: linux
                        
    - name: Download and unzip linux repository, and build the unzipped source code
      shell: bash
      run: |
        wget -qq https://github.com/ChoiDM/linux/archive/${{ steps.vars.outputs.sha_short }}.zip -O linux_down.zip
        unzip -qq linux_down.zip -d linux_down
        ./install-deps.sh
        ./build-linux.sh linux_down tinyconfig
