name: Part C-2. test.yml

on:
  push:
    paths:
      - test
      - test/**
      - test/*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Make compilation.
      run: make -C test > compile.log

